[lint]
select = ["ALL"]
ignore = [
    # groups
    "ANN",  # use mypy for annotations
    "COM",  # turn off weird comma rules
    "D",    # docstrings
    "EM",   # string messages for exceptions
    "FA",   # use typing imports
    "FBT",  # bool arguments
    "PTH",  # os instead of Pathlib when useful
    "RET",  # format returns as needed for readability
    "T20",  # printing allowed
    "TC",   # type checking linter works really badly

    # naming - we allow uppercase letters, e.g. X_train, use_3D
    "N802",
    "N803",
    "N806",

    # various other things
    "B028",     # simple warnings
    "C408",     # call dict(), list(), set()
    "C901",     # complex code
    "E731",     # Lambda expressions
    "PD011",    # Pandas .values
    "PERF203",  # `try`-`except` within a loop incurs performance overhead
    "PGH003",   # ignore types where necessary
    "PLC0415",  # imports inside functions/methods
    "PLR2004",  # numerical constants
    "PLR0913",  # many arguments
    "PLW2901",  # overwrite loop variable for readability
    "PT011",    # use ValueError
    "PYI041",   # explicitly mark Union[int, float] for readability
    "RUF002",   # regular minus sign in docs
    "RUF059",   # unused variables after unpacking
    "RUF012",   # mutable class attributes
    "SLF001",   # use private members
    "SIM108",   # if/else instead of ternary if when we need
    "TRY003",   # long error messages
]

[lint.pycodestyle]
# formatter will reformat lines to length 88, so we report errors only for
# extremely long lines
max-line-length = 200

[lint.mccabe]
max-complexity = 10 # B in xenon rating
